{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "51468f20",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing: testcases/h_functional/05_param_name.sy\n",
      "  Compiler Error: testcases/h_functional/05_param_name.sy\n",
      "    \n",
      "Processing: testcases/h_functional/39_fp_params.sy\n",
      "  Compiler Error: testcases/h_functional/39_fp_params.sy\n",
      "    \n",
      "Processing: testcases/h_functional/24_array_only.sy\n",
      "  Compiler Error: testcases/h_functional/24_array_only.sy\n",
      "    \n",
      "Processing: testcases/h_functional/06_func_name.sy\n",
      "  Assembler Error: testcases/h_functional/06_func_name.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/h_functional/08_global_arr_init.sy\n",
      "  Assembler Error: testcases/h_functional/08_global_arr_init.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/h_functional/36_rotate.sy\n",
      "  Compiler Error: testcases/h_functional/36_rotate.sy\n",
      "    \n",
      "Processing: testcases/h_functional/22_matrix_multiply.sy\n",
      "  Compiler Error: testcases/h_functional/22_matrix_multiply.sy\n",
      "    \n",
      "Processing: testcases/h_functional/25_scope3.sy\n",
      "  Compiler Error: testcases/h_functional/25_scope3.sy\n",
      "    \n",
      "Processing: testcases/h_functional/27_scope5.sy\n",
      "  Compiler Error: testcases/h_functional/27_scope5.sy\n",
      "    \n",
      "Processing: testcases/h_functional/00_comment2.sy\n",
      "  Assembler Error: testcases/h_functional/00_comment2.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/h_functional/04_break_continue.sy\n",
      "  Compiler Error: testcases/h_functional/04_break_continue.sy\n",
      "    \n",
      "Processing: testcases/h_functional/01_multiple_returns.sy\n",
      "  Assembler Error: testcases/h_functional/01_multiple_returns.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/h_functional/30_many_dimensions.sy\n",
      "  Compiler Error: testcases/h_functional/30_many_dimensions.sy\n",
      "    \n",
      "Processing: testcases/h_functional/17_maximal_clique.sy\n",
      "  Compiler Error: testcases/h_functional/17_maximal_clique.sy\n",
      "    \n",
      "Processing: testcases/h_functional/31_many_indirections.sy\n",
      "  Compiler Error: testcases/h_functional/31_many_indirections.sy\n",
      "    \n",
      "Processing: testcases/h_functional/11_BST.sy\n",
      "  Compiler Error: testcases/h_functional/11_BST.sy\n",
      "    \n",
      "Processing: testcases/h_functional/15_graph_coloring.sy\n",
      "  Compiler Error: testcases/h_functional/15_graph_coloring.sy\n",
      "    \n",
      "Processing: testcases/h_functional/26_scope4.sy\n",
      "  Compiler Error: testcases/h_functional/26_scope4.sy\n",
      "    \n",
      "Processing: testcases/h_functional/12_DSU.sy\n",
      "  Compiler Error: testcases/h_functional/12_DSU.sy\n",
      "    \n",
      "Processing: testcases/h_functional/18_prim.sy\n",
      "  Compiler Error: testcases/h_functional/18_prim.sy\n",
      "    \n",
      "Processing: testcases/h_functional/28_side_effect2.sy\n",
      "  Compiler Error: testcases/h_functional/28_side_effect2.sy\n",
      "    \n",
      "Processing: testcases/h_functional/07_arr_init_nd.sy\n",
      "  Assembler Error: testcases/h_functional/07_arr_init_nd.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/h_functional/32_many_params3.sy\n",
      "  Compiler Error: testcases/h_functional/32_many_params3.sy\n",
      "    \n",
      "Processing: testcases/h_functional/20_sort.sy\n",
      "  Compiler Error: testcases/h_functional/20_sort.sy\n",
      "    \n",
      "Processing: testcases/h_functional/33_multi_branch.sy\n",
      "  Compiler Error: testcases/h_functional/33_multi_branch.sy\n",
      "    \n",
      "Processing: testcases/h_functional/38_light2d.sy\n",
      "  Compiler Error: testcases/h_functional/38_light2d.sy\n",
      "    \n",
      "Processing: testcases/h_functional/35_math.sy\n",
      "  Compiler Error: testcases/h_functional/35_math.sy\n",
      "    \n",
      "Processing: testcases/h_functional/13_LCA.sy\n",
      "  Compiler Error: testcases/h_functional/13_LCA.sy\n",
      "    \n",
      "Processing: testcases/h_functional/37_dct.sy\n",
      "  Compiler Error: testcases/h_functional/37_dct.sy\n",
      "    \n",
      "Processing: testcases/h_functional/16_k_smallest.sy\n",
      "  Compiler Error: testcases/h_functional/16_k_smallest.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/h_functional/34_multi_loop.sy\n",
      "  Compiler Error: testcases/h_functional/34_multi_loop.sy\n",
      "    \n",
      "Processing: testcases/h_functional/29_long_line.sy\n",
      "  Compiler Error: testcases/h_functional/29_long_line.sy\n",
      "    \n",
      "Processing: testcases/h_functional/02_ret_in_block.sy\n",
      "  Compiler Error: testcases/h_functional/02_ret_in_block.sy\n",
      "    \n",
      "Processing: testcases/h_functional/03_branch.sy\n",
      "  Compiler Error: testcases/h_functional/03_branch.sy\n",
      "    \n",
      "Processing: testcases/h_functional/19_search.sy\n",
      "  Compiler Error: testcases/h_functional/19_search.sy\n",
      "    \n",
      "Processing: testcases/h_functional/23_json.sy\n",
      "  Compiler Error: testcases/h_functional/23_json.sy\n",
      "    \n",
      "Processing: testcases/h_functional/14_dp.sy\n",
      "  Compiler Error: testcases/h_functional/14_dp.sy\n",
      "    \n",
      "Processing: testcases/h_functional/21_union_find.sy\n",
      "  Compiler Error: testcases/h_functional/21_union_find.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/h_functional/09_BFS.sy\n",
      "  Compiler Error: testcases/h_functional/09_BFS.sy\n",
      "    \n",
      "Processing: testcases/h_functional/10_DFS.sy\n",
      "  Compiler Error: testcases/h_functional/10_DFS.sy\n",
      "    \n",
      "Processing: testcases/functional/76_n_queens.sy\n",
      "  Compiler Error: testcases/functional/76_n_queens.sy\n",
      "    \n",
      "Processing: testcases/functional/71_full_conn.sy\n",
      "  Compiler Error: testcases/functional/71_full_conn.sy\n",
      "    \n",
      "Processing: testcases/functional/80_chaos_token.sy\n",
      "  Compiler Error: testcases/functional/80_chaos_token.sy\n",
      "    \n",
      "Processing: testcases/functional/59_sort_test5.sy\n",
      "  Compiler Error: testcases/functional/59_sort_test5.sy\n",
      "    \n",
      "Processing: testcases/functional/27_while_test2.sy\n",
      "  Compiler Error: testcases/functional/27_while_test2.sy\n",
      "    \n",
      "Processing: testcases/functional/93_nested_calls.sy\n",
      "  Compiler Error: testcases/functional/93_nested_calls.sy\n",
      "    \n",
      "Processing: testcases/functional/21_if_test2.sy\n",
      "  Compiler Error: testcases/functional/21_if_test2.sy\n",
      "    \n",
      "Processing: testcases/functional/10_var_defn_func.sy\n",
      "  Assembler Error: testcases/functional/10_var_defn_func.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/48_assign_complex_expr.sy\n",
      "  Compiler Error: testcases/functional/48_assign_complex_expr.sy\n",
      "    \n",
      "Processing: testcases/functional/81_skip_spaces.sy\n",
      "  Compiler Error: testcases/functional/81_skip_spaces.sy\n",
      "    \n",
      "Processing: testcases/functional/41_unary_op2.sy\n",
      "  Compiler Error: testcases/functional/41_unary_op2.sy\n",
      "    \n",
      "Processing: testcases/functional/96_matrix_add.sy\n",
      "  Compiler Error: testcases/functional/96_matrix_add.sy\n",
      "    \n",
      "Processing: testcases/functional/88_many_params2.sy\n",
      "  Compiler Error: testcases/functional/88_many_params2.sy\n",
      "    \n",
      "Processing: testcases/functional/90_many_locals.sy\n",
      "  Compiler Error: testcases/functional/90_many_locals.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/functional/45_comment1.sy\n",
      "  Assembler Error: testcases/functional/45_comment1.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/23_if_test4.sy\n",
      "  Compiler Error: testcases/functional/23_if_test4.sy\n",
      "    \n",
      "Processing: testcases/functional/37_op_priority3.sy\n",
      "  Compiler Error: testcases/functional/37_op_priority3.sy\n",
      "    \n",
      "Processing: testcases/functional/86_long_code2.sy\n",
      "  Compiler Error: testcases/functional/86_long_code2.sy\n",
      "    \n",
      "Processing: testcases/functional/87_many_params.sy\n",
      "  Compiler Error: testcases/functional/87_many_params.sy\n",
      "    \n",
      "Processing: testcases/functional/84_long_array2.sy\n",
      "  Compiler Error: testcases/functional/84_long_array2.sy\n",
      "    \n",
      "Processing: testcases/functional/66_exgcd.sy\n",
      "  Compiler Error: testcases/functional/66_exgcd.sy\n",
      "    \n",
      "Processing: testcases/functional/13_sub2.sy\n",
      "  Compiler Error: testcases/functional/13_sub2.sy\n",
      "    \n",
      "Processing: testcases/functional/46_hex_defn.sy\n",
      "  Assembler Error: testcases/functional/46_hex_defn.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/58_sort_test4.sy\n",
      "  Compiler Error: testcases/functional/58_sort_test4.sy\n",
      "    \n",
      "Processing: testcases/functional/05_arr_defn4.sy\n",
      "  Compiler Error: testcases/functional/05_arr_defn4.sy\n",
      "    \n",
      "Processing: testcases/functional/18_divc.sy\n",
      "  Assembler Error: testcases/functional/18_divc.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/43_logi_assign.sy\n",
      "  Compiler Error: testcases/functional/43_logi_assign.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/functional/11_add2.sy\n",
      "  Assembler Error: testcases/functional/11_add2.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/28_while_test3.sy\n",
      "  Compiler Error: testcases/functional/28_while_test3.sy\n",
      "    \n",
      "Processing: testcases/functional/20_rem.sy\n",
      "  Compiler Error: testcases/functional/20_rem.sy\n",
      "    \n",
      "Processing: testcases/functional/03_arr_defn2.sy\n",
      "  Assembler Error: testcases/functional/03_arr_defn2.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/51_short_circuit3.sy\n",
      "  Compiler Error: testcases/functional/51_short_circuit3.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/functional/74_kmp.sy\n",
      "  Compiler Error: testcases/functional/74_kmp.sy\n",
      "    \n",
      "Processing: testcases/functional/29_break.sy\n",
      "  Compiler Error: testcases/functional/29_break.sy\n",
      "    \n",
      "Processing: testcases/functional/32_while_if_test2.sy\n",
      "  Compiler Error: testcases/functional/32_while_if_test2.sy\n",
      "    \n",
      "Processing: testcases/functional/16_mulc.sy\n",
      "  Assembler Error: testcases/functional/16_mulc.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/62_percolation.sy\n",
      "  Compiler Error: testcases/functional/62_percolation.sy\n",
      "    \n",
      "Processing: testcases/functional/36_op_priority2.sy\n",
      "  Assembler Error: testcases/functional/36_op_priority2.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/31_while_if_test1.sy\n",
      "  Compiler Error: testcases/functional/31_while_if_test1.sy\n",
      "    \n",
      "Processing: testcases/functional/42_empty_stmt.sy\n",
      "  Compiler Error: testcases/functional/42_empty_stmt.sy\n",
      "    \n",
      "Processing: testcases/functional/12_addc.sy\n",
      "  Assembler Error: testcases/functional/12_addc.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/52_scope.sy\n",
      "  Compiler Error: testcases/functional/52_scope.sy\n",
      "    \n",
      "Processing: testcases/functional/15_mul.sy\n",
      "  Assembler Error: testcases/functional/15_mul.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/63_big_int_mul.sy\n",
      "  Compiler Error: testcases/functional/63_big_int_mul.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/functional/54_hidden_var.sy\n",
      "  Compiler Error: testcases/functional/54_hidden_var.sy\n",
      "    \n",
      "Processing: testcases/functional/61_sort_test7.sy\n",
      "  Compiler Error: testcases/functional/61_sort_test7.sy\n",
      "    \n",
      "Processing: testcases/functional/92_register_alloc.sy\n",
      "  Compiler Error: testcases/functional/92_register_alloc.sy\n",
      "    \n",
      "Processing: testcases/functional/56_sort_test2.sy\n",
      "  Compiler Error: testcases/functional/56_sort_test2.sy\n",
      "    \n",
      "Processing: testcases/functional/60_sort_test6.sy\n",
      "  Compiler Error: testcases/functional/60_sort_test6.sy\n",
      "    \n",
      "Processing: testcases/functional/79_var_name.sy\n",
      "  Compiler Error: testcases/functional/79_var_name.sy\n",
      "    \n",
      "Processing: testcases/functional/98_matrix_mul.sy\n",
      "  Compiler Error: testcases/functional/98_matrix_mul.sy\n",
      "    \n",
      "Processing: testcases/functional/07_const_var_defn3.sy\n",
      "  Assembler Error: testcases/functional/07_const_var_defn3.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/09_func_defn.sy\n",
      "  Compiler Error: testcases/functional/09_func_defn.sy\n",
      "    \n",
      "Processing: testcases/functional/85_long_code.sy\n",
      "  Compiler Error: testcases/functional/85_long_code.sy\n",
      "    \n",
      "Processing: testcases/functional/70_dijkstra.sy\n",
      "  Compiler Error: testcases/functional/70_dijkstra.sy\n",
      "    \n",
      "Processing: testcases/functional/02_var_defn3.sy\n",
      "  Assembler Error: testcases/functional/02_var_defn3.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/40_unary_op.sy\n",
      "  Compiler Error: testcases/functional/40_unary_op.sy\n",
      "    \n",
      "Processing: testcases/functional/75_max_flow.sy\n",
      "  Compiler Error: testcases/functional/75_max_flow.sy\n",
      "    \n",
      "Processing: testcases/functional/01_var_defn2.sy\n",
      "  Assembler Error: testcases/functional/01_var_defn2.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/00_main.sy\n",
      "  Assembler Error: testcases/functional/00_main.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/08_const_array_defn.sy\n",
      "  Assembler Error: testcases/functional/08_const_array_defn.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/82_long_func.sy\n",
      "  Compiler Error: testcases/functional/82_long_func.sy\n",
      "    \n",
      "Processing: testcases/functional/83_long_array.sy\n",
      "  Compiler Error: testcases/functional/83_long_array.sy\n",
      "    \n",
      "Processing: testcases/functional/68_brainfk.sy\n",
      "  Compiler Error: testcases/functional/68_brainfk.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/functional/33_while_if_test3.sy\n",
      "  Compiler Error: testcases/functional/33_while_if_test3.sy\n",
      "    \n",
      "Processing: testcases/functional/50_short_circuit.sy\n",
      "  Compiler Error: testcases/functional/50_short_circuit.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/functional/94_nested_loops.sy\n",
      "  Compiler Error: testcases/functional/94_nested_loops.sy\n",
      "    \n",
      "Processing: testcases/functional/25_while_if.sy\n",
      "  Compiler Error: testcases/functional/25_while_if.sy\n",
      "    \n",
      "Processing: testcases/functional/30_continue.sy\n",
      "  Compiler Error: testcases/functional/30_continue.sy\n",
      "    \n",
      "Processing: testcases/functional/39_op_priority5.sy\n",
      "  Assembler Error: testcases/functional/39_op_priority5.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/91_many_locals2.sy\n",
      "  Compiler Error: testcases/functional/91_many_locals2.sy\n",
      "    \n",
      "Processing: testcases/functional/24_if_test5.sy\n",
      "  Compiler Error: testcases/functional/24_if_test5.sy\n",
      "    \n",
      "Processing: testcases/functional/49_if_complex_expr.sy\n",
      "  Compiler Error: testcases/functional/49_if_complex_expr.sy\n",
      "    \n",
      "Processing: testcases/functional/89_many_globals.sy\n",
      "  Compiler Error: testcases/functional/89_many_globals.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/functional/34_arr_expr_len.sy\n",
      "  Compiler Error: testcases/functional/34_arr_expr_len.sy\n",
      "    \n",
      "Processing: testcases/functional/67_reverse_output.sy\n",
      "  Compiler Error: testcases/functional/67_reverse_output.sy\n",
      "    \n",
      "Processing: testcases/functional/22_if_test3.sy\n",
      "  Compiler Error: testcases/functional/22_if_test3.sy\n",
      "    \n",
      "Processing: testcases/functional/26_while_test1.sy\n",
      "  Compiler Error: testcases/functional/26_while_test1.sy\n",
      "    \n",
      "Processing: testcases/functional/77_substr.sy\n",
      "  Compiler Error: testcases/functional/77_substr.sy\n",
      "    \n",
      "Processing: testcases/functional/44_stmt_expr.sy\n",
      "  Compiler Error: testcases/functional/44_stmt_expr.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/functional/14_subc.sy\n",
      "  Compiler Error: testcases/functional/14_subc.sy\n",
      "    \n",
      "Processing: testcases/functional/17_div.sy\n",
      "  Assembler Error: testcases/functional/17_div.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/53_scope2.sy\n",
      "  Compiler Error: testcases/functional/53_scope2.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/functional/04_arr_defn3.sy\n",
      "  Compiler Error: testcases/functional/04_arr_defn3.sy\n",
      "    \n",
      "Processing: testcases/functional/38_op_priority4.sy\n",
      "  Compiler Error: testcases/functional/38_op_priority4.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/functional/99_matrix_tran.sy\n",
      "  Compiler Error: testcases/functional/99_matrix_tran.sy\n",
      "    \n",
      "Processing: testcases/functional/06_const_var_defn2.sy\n",
      "  Assembler Error: testcases/functional/06_const_var_defn2.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/73_int_io.sy\n",
      "  Compiler Error: testcases/functional/73_int_io.sy\n",
      "    \n",
      "Processing: testcases/functional/95_float.sy\n",
      "  Compiler Error: testcases/functional/95_float.sy\n",
      "    \n",
      "Processing: testcases/functional/35_op_priority1.sy\n",
      "  Assembler Error: testcases/functional/35_op_priority1.sy\n",
      "    /usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find crt0.o: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lm: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lc: No such file or directory\n",
      "/usr/lib/gcc/riscv64-unknown-elf/13.2.0/../../../riscv64-unknown-elf/bin/ld: cannot find -lgloss: No such file or directory\n",
      "collect2: error: ld returned 1 exit status\n",
      "Processing: testcases/functional/65_color.sy\n",
      "  Compiler Error: testcases/functional/65_color.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/functional/57_sort_test3.sy\n",
      "  Compiler Error: testcases/functional/57_sort_test3.sy\n",
      "    \n",
      "Processing: testcases/functional/55_sort_test1.sy\n",
      "  Compiler Error: testcases/functional/55_sort_test1.sy\n",
      "    \n",
      "Processing: testcases/functional/72_hanoi.sy\n",
      "  Compiler Error: testcases/functional/72_hanoi.sy\n",
      "    \n",
      "Processing: testcases/functional/69_expr_eval.sy\n",
      "  Compiler Error: testcases/functional/69_expr_eval.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/functional/64_calculator.sy\n",
      "  Compiler Error: testcases/functional/64_calculator.sy\n",
      "    \n",
      "Processing: testcases/functional/47_hex_oct_add.sy\n",
      "  Compiler Error: testcases/functional/47_hex_oct_add.sy\n",
      "    \n",
      "Processing: testcases/functional/19_mod.sy\n",
      "  Compiler Error: testcases/functional/19_mod.sy\n",
      "    \n",
      "Processing: testcases/functional/97_matrix_sub.sy\n",
      "  Compiler Error: testcases/functional/97_matrix_sub.sy\n",
      "    \n",
      "Processing: testcases/functional/78_side_effect.sy\n",
      "  Compiler Error: testcases/functional/78_side_effect.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-Z3A-28.sy\n",
      "  Compiler Error: testcases/performance/2024-Z3A-28.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/performance/2024-VGH-20.sy\n",
      "  Compiler Error: testcases/performance/2024-VGH-20.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/performance/2024-XRB-24.sy\n",
      "  Compiler Error: testcases/performance/2024-XRB-24.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-OBF-29.sy\n",
      "  Compiler Error: testcases/performance/2024-OBF-29.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-BJV-10.sy\n",
      "  Compiler Error: testcases/performance/2024-BJV-10.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-5NG-2.sy\n",
      "  Compiler Error: testcases/performance/2024-5NG-2.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/performance/2024-FQX-25.sy\n",
      "  Compiler Error: testcases/performance/2024-FQX-25.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-ETJ-33.sy\n",
      "  Compiler Error: testcases/performance/2024-ETJ-33.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-QV9-34.sy\n",
      "  Compiler Error: testcases/performance/2024-QV9-34.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/performance/2024-IG5-12.sy\n",
      "  Compiler Error: testcases/performance/2024-IG5-12.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-U7W-16.sy\n",
      "  Compiler Error: testcases/performance/2024-U7W-16.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-LW8-7.sy\n",
      "  Compiler Error: testcases/performance/2024-LW8-7.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-T6G-27.sy\n",
      "  Compiler Error: testcases/performance/2024-T6G-27.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/performance/2024-XU5-13.sy\n",
      "  Compiler Error: testcases/performance/2024-XU5-13.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-JR2-21.sy\n",
      "  Compiler Error: testcases/performance/2024-JR2-21.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-TBR-19.sy\n",
      "  Compiler Error: testcases/performance/2024-TBR-19.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-V6O-23.sy\n",
      "  Compiler Error: testcases/performance/2024-V6O-23.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-BE3-31.sy\n",
      "  Compiler Error: testcases/performance/2024-BE3-31.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-I9Y-15.sy\n",
      "  Compiler Error: testcases/performance/2024-I9Y-15.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-PAF-17.sy\n",
      "  Compiler Error: testcases/performance/2024-PAF-17.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/performance/2024-K22-4.sy\n",
      "  Compiler Error: testcases/performance/2024-K22-4.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-FI8-9.sy\n",
      "  Compiler Error: testcases/performance/2024-FI8-9.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-1RK-26.sy\n",
      "  Compiler Error: testcases/performance/2024-1RK-26.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-U7D-6.sy\n",
      "  Compiler Error: testcases/performance/2024-U7D-6.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-VRT-1.sy\n",
      "  Compiler Error: testcases/performance/2024-VRT-1.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-51P-30.sy\n",
      "  Compiler Error: testcases/performance/2024-51P-30.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-CH1-5.sy\n",
      "  Compiler Error: testcases/performance/2024-CH1-5.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-X7M-3.sy\n",
      "  Compiler Error: testcases/performance/2024-X7M-3.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/performance/2024-AZ7-32.sy\n",
      "  Compiler Error: testcases/performance/2024-AZ7-32.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-84M-11.sy\n",
      "  Compiler Error: testcases/performance/2024-84M-11.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/performance/2024-PCT-14.sy\n",
      "  Compiler Error: testcases/performance/2024-PCT-14.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-Y60-18.sy\n",
      "  Compiler Error: testcases/performance/2024-Y60-18.sy\n",
      "    \n",
      "Processing: testcases/performance/2024-5HA-8.sy\n",
      "  Compiler Error: testcases/performance/2024-5HA-8.sy\n",
      "    Compiler: /home/dh/Compiler/Compiler/MyBackend/RISCVContext.cpp:48: void RISCVContext::extraDealStoreInst(RISCVInst*, StoreInst*): Assertion `allocInst && \"must not be nullptr\"' failed.\n",
      "Processing: testcases/performance/2024-2D0-22.sy\n",
      "  Compiler Error: testcases/performance/2024-2D0-22.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-PKP-8.sy\n",
      "  Compiler Error: testcases/h_performance/2024-PKP-8.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-LN4-9.sy\n",
      "  Compiler Error: testcases/h_performance/2024-LN4-9.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/h_performance/2024-K0I-17.sy\n",
      "  Compiler Error: testcases/h_performance/2024-K0I-17.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-NKK-22.sy\n",
      "  Compiler Error: testcases/h_performance/2024-NKK-22.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-FVJ-15.sy\n",
      "  Compiler Error: testcases/h_performance/2024-FVJ-15.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/h_performance/2024-CH6-24.sy\n",
      "  Compiler Error: testcases/h_performance/2024-CH6-24.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-I4W-2.sy\n",
      "  Compiler Error: testcases/h_performance/2024-I4W-2.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-BAV-3.sy\n",
      "  Compiler Error: testcases/h_performance/2024-BAV-3.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/h_performance/2024-C64-14.sy\n",
      "  Compiler Error: testcases/h_performance/2024-C64-14.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-0ZE-13.sy\n",
      "  Compiler Error: testcases/h_performance/2024-0ZE-13.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-NCY-23.sy\n",
      "  Compiler Error: testcases/h_performance/2024-NCY-23.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/h_performance/2024-NT1-4.sy\n",
      "  Compiler Error: testcases/h_performance/2024-NT1-4.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-FAF-19.sy\n",
      "  Compiler Error: testcases/h_performance/2024-FAF-19.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-931-6.sy\n",
      "  Compiler Error: testcases/h_performance/2024-931-6.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-MXP-16.sy\n",
      "  Compiler Error: testcases/h_performance/2024-MXP-16.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-2KM-21.sy\n",
      "  Compiler Error: testcases/h_performance/2024-2KM-21.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-U03-25.sy\n",
      "  Compiler Error: testcases/h_performance/2024-U03-25.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/h_performance/2024-1WO-11.sy\n",
      "  Compiler Error: testcases/h_performance/2024-1WO-11.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-JVU-10.sy\n",
      "  Compiler Error: testcases/h_performance/2024-JVU-10.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-VTF-5.sy\n",
      "  Compiler Error: testcases/h_performance/2024-VTF-5.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-7UJ-12.sy\n",
      "  Compiler Error: testcases/h_performance/2024-7UJ-12.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-KVV-20.sy\n",
      "  Compiler Error: testcases/h_performance/2024-KVV-20.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-H17-1.sy\n",
      "  Compiler Error: testcases/h_performance/2024-H17-1.sy\n",
      "    \n",
      "Processing: testcases/h_performance/2024-DCV-7.sy\n",
      "  Compiler Error: testcases/h_performance/2024-DCV-7.sy\n",
      "    terminate called after throwing an instance of 'std::invalid_argument'\n",
      "  what():  stoi\n",
      "Processing: testcases/h_performance/2024-8NL-18.sy\n",
      "  Compiler Error: testcases/h_performance/2024-8NL-18.sy\n",
      "    \n",
      "\n",
      "===== Test Summary =====\n",
      "Compiler Error: Total: 199\n",
      "Runtime Error: Total: 0\n",
      "Timeout Error: Total: 0\n",
      "Wrong Answer: Total: 0\n",
      "TimeOut Function: 0\n",
      "Bad Test: Total: 0\n",
      "Accepted: Total: 0\n",
      "TOTAL TIME: 0.000 seconds\n",
      "========================\n",
      "\n",
      "Detailed report saved to: ./output/test_report.log\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python3\n",
    "import os\n",
    "import sys\n",
    "import subprocess\n",
    "import time\n",
    "import difflib\n",
    "import re\n",
    "\n",
    "COMPILER_PATH = \"./build/Compiler\"  # 编译器路径\n",
    "TESTCASE_DIR = \"testcases\"          # 测试用例目录\n",
    "COMPARATOR = \"/usr/bin/riscv64-unknown-elf-gcc\" \n",
    "QEMU_PATH = \"qemu-riscv64\"          # RISC-V模拟器\n",
    "TIMEOUT_DURATION = 2                # 运行超时阈值(秒)\n",
    "COMPILE_TIMEOUT = 60                # 编译超时阈值(秒)\n",
    "OUTPUT_DIR = \"./output\"             # 输出目录（仅用于.bin和.actual文件）\n",
    "\n",
    "# ===== 初始化统计变量 =====\n",
    "CE_list = []      # 编译错误\n",
    "RE_list = []      # 运行时错误\n",
    "TLE_list = []     # 超时错误\n",
    "WA_list = []      # 错误答案\n",
    "AC_list = []      # 通过用例\n",
    "Time_Out = []     # 超时函数\n",
    "Bad_test = []     # 无效测试\n",
    "total_time = 0    # 总耗时\n",
    "\n",
    "# ===== 准备输出目录 =====\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)  # 仅用于.bin和.actual文件\n",
    "\n",
    "# ===== 收集测试用例 =====\n",
    "test_list = []\n",
    "for root, dirs, files in os.walk(TESTCASE_DIR):\n",
    "    for file in files:\n",
    "        if file.endswith(\".sy\"):\n",
    "            test_list.append(os.path.join(root, file))\n",
    "\n",
    "# ===== 主测试循环 =====\n",
    "for test in test_list:\n",
    "    base_name = os.path.basename(test).replace(\".sy\", \"\")\n",
    "    base_path = os.path.dirname(test)\n",
    "    out_file = os.path.join(base_path, base_name + \".out\")\n",
    "    in_file = os.path.join(base_path, base_name + \".in\")\n",
    "    # .s文件生成在.sy文件同目录下\n",
    "    s_file = os.path.join(base_path, base_name + \".s\")\n",
    "    bin_file = os.path.join(OUTPUT_DIR, base_name + \".bin\")\n",
    "    actual_out = os.path.join(OUTPUT_DIR, base_name + \".actual\")\n",
    "    \n",
    "    print(f\"Processing: {test}\")\n",
    "\n",
    "    # 检查.out文件是否存在\n",
    "    if not os.path.exists(out_file):\n",
    "        Bad_test.append(test)\n",
    "        print(f\"  Bad Test: Missing .out file for {test}\")\n",
    "        continue\n",
    "\n",
    "    # === 步骤1: 编译源文件生成汇编 ===\n",
    "    try:\n",
    "        compile_args = [COMPILER_PATH, test, \"-o\", s_file]\n",
    "        # 添加--march选项传递给编译器（如果需要）\n",
    "        # compile_args += [\"--march=rv64gc\"]\n",
    "        subprocess.run(compile_args, timeout=COMPILE_TIMEOUT, check=True,\n",
    "                       stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n",
    "    except subprocess.TimeoutExpired:\n",
    "        CE_list.append(test)\n",
    "        Time_Out.append(test)\n",
    "        print(f\"  Compiler Timeout: {test}\")\n",
    "        continue\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        CE_list.append(test)\n",
    "        print(f\"  Compiler Error: {test}\\n    {e.stderr.decode().strip()}\")\n",
    "        continue\n",
    "    \n",
    "    # === 步骤2: 编译汇编生成可执行文件（使用图片中的参数）===\n",
    "    try:\n",
    "        # 核心修改：添加rv64gc选项（G=IMAFFD，C=压缩指令）\n",
    "        assemble_args = [\n",
    "            COMPARATOR, \n",
    "            \"-static\", \n",
    "            \"-march=rv64gc\",  # 使用图片中的精确参数\n",
    "            \"-mabi=lp64\",     # 64位ABI\n",
    "            s_file, \n",
    "            \"-o\", \n",
    "            bin_file,\n",
    "            \"-lm\"             # 链接数学库（如果有浮点运算）\n",
    "        ]\n",
    "        subprocess.run(assemble_args, timeout=TIMEOUT_DURATION, check=True,\n",
    "                       stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n",
    "    except subprocess.TimeoutExpired:\n",
    "        CE_list.append(test)\n",
    "        Time_Out.append(test)\n",
    "        print(f\"  Assembler Timeout: {test}\")\n",
    "        continue\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        # 详细输出汇编器错误信息\n",
    "        error_msg = e.stderr.decode().strip()\n",
    "        CE_list.append(test)\n",
    "        print(f\"  Assembler Error: {test}\\n    {error_msg}\")\n",
    "        \n",
    "        # 保存汇编错误日志以便调试\n",
    "        asm_error_log = os.path.join(base_path, base_name + \"_asm_error.log\")\n",
    "        with open(asm_error_log, \"w\") as err_file:\n",
    "            err_file.write(f\"Assembler command: {' '.join(assemble_args)}\\n\")\n",
    "            err_file.write(f\"Error details:\\n{error_msg}\\n\")\n",
    "        continue\n",
    "    except FileNotFoundError:\n",
    "        CE_list.append(test)\n",
    "        print(f\"  Error: Assembler not found at {COMPARATOR}\")\n",
    "        continue\n",
    "    \n",
    "    # === 步骤3: 执行测试并计时 ===\n",
    "    start_time = time.time()\n",
    "    try:\n",
    "        # 准备输入数据\n",
    "        input_data = None\n",
    "        if os.path.exists(in_file):\n",
    "            with open(in_file, \"rb\") as f:\n",
    "                input_data = f.read()\n",
    "        \n",
    "        # 执行程序（指定64位架构）\n",
    "        run_args = [QEMU_PATH, \"-cpu\", \"rv64\", bin_file]\n",
    "        result = subprocess.run(run_args, input=input_data, timeout=TIMEOUT_DURATION,\n",
    "                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n",
    "        elapsed = time.time() - start_time\n",
    "        total_time += elapsed\n",
    "        \n",
    "        # 处理输出\n",
    "        output = result.stdout.decode(errors=\"ignore\")\n",
    "        if not output.endswith('\\n'):\n",
    "            output += '\\n'\n",
    "        output += str(result.returncode) + '\\n'\n",
    "        \n",
    "        with open(actual_out, \"w\") as f:\n",
    "            f.write(output)\n",
    "    \n",
    "    except subprocess.TimeoutExpired:\n",
    "        TLE_list.append(test)\n",
    "        Time_Out.append(test)\n",
    "        total_time += TIMEOUT_DURATION\n",
    "        print(f\"  Timeout Error: {test}\")\n",
    "        continue\n",
    "    except Exception as e:\n",
    "        # 保存运行错误日志\n",
    "        runtime_error_log = os.path.join(OUTPUT_DIR, base_name + \"_runtime_error.log\")\n",
    "        with open(runtime_error_log, \"w\") as err_file:\n",
    "            err_file.write(f\"Runtime error: {str(e)}\\n\")\n",
    "            if result:\n",
    "                err_file.write(f\"Stdout: {result.stdout.decode(errors='ignore')}\\n\")\n",
    "                err_file.write(f\"Stderr: {result.stderr.decode(errors='ignore')}\\n\")\n",
    "                \n",
    "        RE_list.append(test)\n",
    "        print(f\"  Runtime Error: {test}\\n    {str(e)}\")\n",
    "        continue\n",
    "    \n",
    "    # === 步骤4: 兼容性更强的输出比较 ===\n",
    "    try:\n",
    "        with open(out_file, \"r\") as f:\n",
    "            expected_output = f.read()\n",
    "        \n",
    "        # 规范化比较（允许±1误差和浮点容错）\n",
    "        def normalize_output(text):\n",
    "            lines = text.strip().splitlines()\n",
    "            # 尝试将数值解析为浮点数，否则保持原字符串\n",
    "            normalized = []\n",
    "            for line in lines:\n",
    "                try:\n",
    "                    # 浮点数容差处理\n",
    "                    val = float(line)\n",
    "                    normalized.append(f\"{val:.6f}\")  # 限制精度\n",
    "                except ValueError:\n",
    "                    # 处理整数/字符串\n",
    "                    normalized.append(line.strip())\n",
    "            return normalized\n",
    "        \n",
    "        norm_output = normalize_output(output)\n",
    "        norm_expected = normalize_output(expected_output)\n",
    "        \n",
    "        # 容错比较\n",
    "        if len(norm_output) != len(norm_expected):\n",
    "            WA_list.append(test)\n",
    "            print(f\"  Wrong Answer: Output line count mismatch\")\n",
    "        else:\n",
    "            all_match = True\n",
    "            for i, (out_line, exp_line) in enumerate(zip(norm_output, norm_expected)):\n",
    "                if out_line != exp_line:\n",
    "                    try:\n",
    "                        # 浮点数容差比较\n",
    "                        out_val = float(out_line)\n",
    "                        exp_val = float(exp_line)\n",
    "                        if abs(out_val - exp_val) > 1e-5:  # 万分之一误差容忍\n",
    "                            all_match = False\n",
    "                    except ValueError:\n",
    "                        all_match = False\n",
    "            \n",
    "            if all_match:\n",
    "                AC_list.append(test)\n",
    "                print(f\"  Accepted: {test} ({elapsed:.3f}s)\")\n",
    "            else:\n",
    "                WA_list.append(test)\n",
    "                print(f\"  Wrong Answer: {test}\")\n",
    "                \n",
    "                # 生成详细差异报告\n",
    "                diff = difflib.unified_diff(\n",
    "                    output.splitlines(), expected_output.splitlines(),\n",
    "                    fromfile=\"Actual\", tofile=\"Expected\", lineterm=''\n",
    "                )\n",
    "                diff_report = os.path.join(OUTPUT_DIR, base_name + \".diff\")\n",
    "                with open(diff_report, \"w\") as df:\n",
    "                    df.write(\"\\n\".join(diff))\n",
    "    except Exception as e:\n",
    "        WA_list.append(test)\n",
    "        print(f\"  Output Comparison Failed: {test}\\n    {str(e)}\")\n",
    "\n",
    "# ===== 打印统计结果 =====\n",
    "print(\"\\n===== Test Summary =====\")\n",
    "print(f\"Compiler Error: Total: {len(CE_list)}\")\n",
    "print(f\"Runtime Error: Total: {len(RE_list)}\")\n",
    "print(f\"Timeout Error: Total: {len(TLE_list)}\")\n",
    "print(f\"Wrong Answer: Total: {len(WA_list)}\")\n",
    "print(f\"TimeOut Function: {len(Time_Out)}\")\n",
    "print(f\"Bad Test: Total: {len(Bad_test)}\")\n",
    "print(f\"Accepted: Total: {len(AC_list)}\")\n",
    "print(f\"TOTAL TIME: {total_time:.3f} seconds\")\n",
    "print(\"========================\")\n",
    "\n",
    "# 保存详细报告\n",
    "with open(os.path.join(OUTPUT_DIR, \"test_report.log\"), \"w\") as report:\n",
    "    report.write(\"===== Detailed Test Report =====\\n\")\n",
    "    report.write(f\"Total Test Cases: {len(test_list)}\\n\\n\")\n",
    "    report.write(f\"Compiler: {COMPILER_PATH}\\n\")\n",
    "    report.write(f\"Assembler: {COMPARATOR}\\n\")\n",
    "    report.write(f\"QEMU: {QEMU_PATH}\\n\")\n",
    "    report.write(f\"Compile Options: -static -march=rv64gc -mabi=lp64\\n\\n\")\n",
    "    \n",
    "    if CE_list:\n",
    "        report.write(\"\\n===== Compiler Errors =====\\n\")\n",
    "        for test in CE_list:\n",
    "            report.write(f\"  {test}\\n\")\n",
    "    \n",
    "    if RE_list:\n",
    "        report.write(\"\\n===== Runtime Errors =====\\n\")\n",
    "        for test in RE_list:\n",
    "            report.write(f\"  {test}\\n\")\n",
    "    \n",
    "    if TLE_list:\n",
    "        report.write(\"\\n===== Timeout Errors =====\\n\")\n",
    "        for test in TLE_list:\n",
    "            report.write(f\"  {test}\\n\")\n",
    "    \n",
    "    if WA_list:\n",
    "        report.write(\"\\n===== Wrong Answers =====\\n\")\n",
    "        for test in WA_list:\n",
    "            report.write(f\"  {test}\\n\")\n",
    "    \n",
    "    if Bad_test:\n",
    "        report.write(\"\\n===== Bad Tests (missing .out) =====\\n\")\n",
    "        for test in Bad_test:\n",
    "            report.write(f\"  {test}\\n\")\n",
    "    \n",
    "    if AC_list:\n",
    "        report.write(\"\\n===== Accepted Tests =====\\n\")\n",
    "        for test in AC_list:\n",
    "            report.write(f\"  {test}\\n\")\n",
    "    \n",
    "    report.write(f\"\\n===== Performance Summary =====\\n\")\n",
    "    report.write(f\"Total Execution Time: {total_time:.3f} seconds\\n\")\n",
    "    if test_list:\n",
    "        avg_time = total_time / len(AC_list) if AC_list else 0\n",
    "        report.write(f\"Average Time per Test: {avg_time:.4f} seconds\\n\")\n",
    "\n",
    "print(f\"\\nDetailed report saved to: {os.path.join(OUTPUT_DIR, 'test_report.log')}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
